name: Staging

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install heroku cli
      run: sudo npm install -g heroku

    - name: Deploy staging app to heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git config user.name "staging-action"
        git config user.email "staging@action.com"
        git add .
        git commit -m"dummy commit for heroku"
        heroku git:remote -a meal-diary-backend-staging
        git push heroku master
